### ISSUE TITLE
stacks and threads causes crash

### ISSUE THREAD

**Issue by grandinj** [KDAB/hotspot#142]
with current master (as of a couple of hours ago)

[noel@libreoffice libo4]$ perf record --call-graph dwarf -s ./instdir/program/soffice.bin ~/Downloads/Phd_text0.65_tisk.docx 
debug:27996:27996: time loading doc 24475
[ perf record: Woken up 5971 times to write data ]
Warning:
Processed 213502 events and lost 126 chunks!

Check IO/CPU overload!

[ perf record: Captured and wrote 1505.595 MB perf.data (186859 samples) ]
[noel@libreoffice libo4]$ hotspot
feature not properly read PerfHeader::Feature(CPU_TOPOLOGY) 412 348
unhandled event type 79
unhandled event type 73
unhandled event type 74
PerfUnwind::ErrorCode(MissingElfFile): Failed to find ELF file for an instruction pointer address. This can break stack unwinding and lead to missing symbols.
PerfUnwind::ErrorCode(InvalidKallsyms): Failed to parse kernel symbol mapping file "/home/noel/.debug/[kernel.kallsyms]/c1328a3968265b75fe9bff043d167789256783c6/kallsyms": Mapping is empty.
Segmentation fault (core dumped)

**Comment by milianw** [comment]
```
0.000 fatal: unknown[/usr/include/qt/QtCore/qvector.h:436]: ASSERT failure in QVector<T>::operator[]: "index out of range", file /usr/include/qt/QtCore/qvector.h, line 436

Thread 5 "GlobalQueue[01]" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffce89b700 (LWP 16884)]
0x00007ffff14a886b in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff14a886b in raise () from /usr/lib/libc.so.6
#1  0x00007ffff149340e in abort () from /usr/lib/libc.so.6
#2  0x00007ffff21e433c in QMessageLogger::fatal(char const*, ...) const () from /usr/lib/libQt5Core.so.5
#3  0x00007ffff21e37c3 in qt_assert_x(char const*, char const*, char const*, int) () from /usr/lib/libQt5Core.so.5
#4  0x0000555555617666 in QVector<long long>::operator[] (this=0x7fffce89aa00, i=-1) at /usr/include/qt/QtCore/qvector.h:436
#5  0x0000555555616f23 in Data::Costs::addTotalCost (this=0x7fffce89a9f0, type=-1, delta=1) at /home/milian/projects/kdab/rnd/hotspot/src/models/data.h:173
#6  0x0000555555616da8 in Data::BottomUpResults::addEvent(int, unsigned long long, QVector<int> const&, std::function<void (Data::Symbol const&, Data::Location const&)> const&) (
    this=0x7fffce89a9c0, type=-1, cost=1, frames=..., frameCallback=...) at /home/milian/projects/kdab/rnd/hotspot/src/models/data.cpp:248
#7  0x00005555555a5e87 in PerfParserPrivate::addSampleToBottomUp (this=0x7fffce89a8a0, sample=..., sampleCost=...)
    at /home/milian/projects/kdab/rnd/hotspot/src/parsers/perf/perfparser.cpp:1030
#8  0x00005555555a59d4 in PerfParserPrivate::addSampleToBottomUp (this=0x7fffce89a8a0, sample=...) at /home/milian/projects/kdab/rnd/hotspot/src/parsers/perf/perfparser.cpp:998
#9  0x00005555555a5830 in PerfParserPrivate::addSample (this=0x7fffce89a8a0, sample=...) at /home/milian/projects/kdab/rnd/hotspot/src/parsers/perf/perfparser.cpp:984
#10 0x00005555555a3441 in PerfParserPrivate::parseEvent (this=0x7fffce89a8a0) at /home/milian/projects/kdab/rnd/hotspot/src/parsers/perf/perfparser.cpp:697
#11 0x00005555555a2a5f in PerfParserPrivate::tryParse (this=0x7fffce89a8a0) at /home/milian/projects/kdab/rnd/hotspot/src/parsers/perf/perfparser.cpp:641
#12 0x0000555555593f4e in PerfParser::<lambda()>::<lambda()>::operator()(void) const (__closure=0x555555ea85c0)
    at /home/milian/projects/kdab/rnd/hotspot/src/parsers/perf/perfparser.cpp:1349
#13 0x000055555559feee in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, PerfParser::startParseFile(const QString&, const QString&, const QString&, const QString&, const QString&, const QString&, const QString&)::<lambda()>::<lambda()> >::call(PerfParser::<lambda()>::<lambda()> &, void **) (f=..., arg=0x7fffce89a190)
    at /usr/include/qt/QtCore/qobjectdefs_impl.h:128
#14 0x000055555559efbb in QtPrivate::Functor<PerfParser::startParseFile(const QString&, const QString&, const QString&, const QString&, const QString&, const QString&, const QString&)::<lambda()>::<lambda()>, 0>::call<QtPrivate::List<>, void>(PerfParser::<lambda()>::<lambda()> &, void *, void **) (f=..., arg=0x7fffce89a190) at /usr/include/qt/QtCore/qobjectdefs_impl.h:238
#15 0x000055555559d5b9 in QtPrivate::QFunctorSlotObject<PerfParser::startParseFile(const QString&, const QString&, const QString&, const QString&, const QString&, const QString&, const QString&)::<lambda()>::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=1, this_=0x555555ea85b0, r=0x7fffce89a8f8, 
    a=0x7fffce89a190, ret=0x0) at /usr/include/qt/QtCore/qobjectdefs_impl.h:421
#16 0x00007ffff23ffc50 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#17 0x00007ffff236db80 in ?? () from /usr/lib/libQt5Core.so.5
#18 0x00007ffff236dee0 in ?? () from /usr/lib/libQt5Core.so.5
#19 0x00007ffff23ffafc in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#20 0x00007ffff240b6fa in QSocketNotifier::activated(int, QSocketNotifier::QPrivateSignal) () from /usr/lib/libQt5Core.so.5
```
