### ISSUE TITLE
segfault on start on Fedora 29

### ISSUE THREAD

**Issue by ks1322** [KDAB/hotspot#166]
```
$ hotspot --version
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
hotspot 1.0.0
$ perf record sleep 1
[ perf record: Woken up 1 times to write data ]
[ perf record: Captured and wrote 0,001 MB perf.data (10 samples) ]
$ hotspot
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
feature not properly read 13 244 212
unhandled event type 79
unhandled event type 73
unhandled event type 74
Segmentation fault (core dumped)
```
```
(gdb) bt
#0  0x000055819feecaca in Data::Costs::ensureSpaceAvailable(int, unsigned int) (id=<optimized out>, type=<optimized out>, this=<optimized out>) at /usr/include/qt5/QtCore/qvector.h:87
#1  0x000055819feecaca in Data::Costs::add(int, unsigned int, long long) (delta=1, id=0, type=-1, this=0x7fabd630bac0) at /usr/src/debug/hotspot-1.0.0-7.fc29.x86_64/src/models/data.h:130
#2  0x000055819feecaca in PerfParserPrivate::addFrame(Data::BottomUp*, int, QSet<Data::Symbol>*, int, unsigned long long) (this=this@entry=0x7fabd630b980, parent=<optimized out>, id=<optimized out>, recursionGuard=recursionGuard@entry=0x7fabd630b5a0, type=-1, period=1) at /usr/src/debug/hotspot-1.0.0-7.fc29.x86_64/src/parsers/perf/perfparser.cpp:813
#3  0x000055819fef0e35 in PerfParserPrivate::addSampleToBottomUp (sample=..., this=0x7fabd630b980) at /usr/src/debug/hotspot-1.0.0-7.fc29.x86_64/src/parsers/perf/perfparser.cpp:863
#4  0x000055819fef0e35 in PerfParserPrivate::addSample (sample=..., this=0x7fabd630b980) at /usr/src/debug/hotspot-1.0.0-7.fc29.x86_64/src/parsers/perf/perfparser.cpp:838
#5  0x000055819fef0e35 in PerfParserPrivate::parseEvent() (this=this@entry=0x7fabd630b980) at /usr/src/debug/hotspot-1.0.0-7.fc29.x86_64/src/parsers/perf/perfparser.cpp:646
#6  0x000055819fee76d1 in PerfParserPrivate::tryParse() (this=0x7fabd630b980) at /usr/src/debug/hotspot-1.0.0-7.fc29.x86_64/src/parsers/perf/perfparser.cpp:598
#7  0x000055819fee76d1 in PerfParser::<lambda()>::<lambda()>::operator() (__closure=<optimized out>) at /usr/src/debug/hotspot-1.0.0-7.fc29.x86_64/src/parsers/perf/perfparser.cpp:1062
#8  0x000055819fee76d1 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, PerfParser::startParseFile(const QString&, const QString&, const QString&, const QString&, const QString&, const QString&, const QString&)::<lambda()>::<lambda()> >::call (arg=<optimized out>, f=...) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:128
#9  0x000055819fee76d1 in QtPrivate::Functor<PerfParser::startParseFile(const QString&, const QString&, const QString&, const QString&, const QString&, const QString&, const QString&)::<lambda()>::<lambda()>, 0>::call<QtPrivate::List<>, void> (arg=<optimized out>, f=...) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:238
#10 0x000055819fee76d1 in QtPrivate::QFunctorSlotObject<PerfParser::startParseFile(const QString&, const QString&, const QString&, const QString&, const QString&, const QString&, const QString&)::<lambda()>::<lambda()>, 0, QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=<optimized out>, this_=0x5581a0b4f800, r=<optimized out>, a=<optimized out>, ret=<optimized out>) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:421
#11 0x00007fabf0b0c1c3 in QMetaObject::activate(QObject*, int, int, void**) () at /lib64/libQt5Core.so.5
#12 0x00007fabf0a8a1bf in  () at /lib64/libQt5Core.so.5
#13 0x00007fabf0a90910 in  () at /lib64/libQt5Core.so.5
#14 0x00007fabf0a85bff in QProcess::waitForFinished(int) () at /lib64/libQt5Core.so.5
#15 0x000055819fee7a47 in PerfParser::<lambda()>::operator()(void) const (__closure=0x5581a0b4e9d0) at /usr/src/debug/hotspot-1.0.0-7.fc29.x86_64/src/parsers/perf/perfparser.cpp:1123
#16 0x00007fabf1d6039c in ThreadWeaver::Executor::run(QSharedPointer<ThreadWeaver::JobInterface> const&, ThreadWeaver::Thread*) () at /lib64/libKF5ThreadWeaver.so.5
#17 0x00007fabf1d5f1c4 in ThreadWeaver::Job::execute(QSharedPointer<ThreadWeaver::JobInterface> const&, ThreadWeaver::Thread*) () at /lib64/libKF5ThreadWeaver.so.5
#18 0x00007fabf1d5ec63 in ThreadWeaver::Thread::run() () at /lib64/libKF5ThreadWeaver.so.5
#19 0x00007fabf09542fb in  () at /lib64/libQt5Core.so.5
#20 0x00007fabf02c658e in start_thread () at /lib64/libpthread.so.0
#21 0x00007fabf04906a3 in clone () at /lib64/libc.so.6
(gdb) 
```

**Comment by ks1322** [comment]
Though I could not reproduce on manually built binary from master.
Could be some already fixed or Fedora specific bug.

**Comment by milianw** [comment]
if it's fixed in master, I'll close this

and yes, I really should create a new stable release for distros to package...
