### ISSUE TITLE
hotspot chrashing on disassembly

### ISSUE THREAD

**Issue by GitMensch** [KDAB/hotspot#604]
**Describe the bug**
SIGSEGV when requesting disassembly.

**To Reproduce**

1. Open recording with that (hint at myself: de5t GD107)
2. Go to caller/callee
3. Search for function (hint: SY948)
4. right click on function to see disassembly
5. chrash

```
hotspot.disassemblyoutput: objdump binary does not support `--visualize-jumps`: "/usr/bin/objdump"
hotspot.disassemblyoutput: objdump binary does not support `--disassembler-color`: "/usr/bin/objdump"
/tmp/.mount_hotspoQTY1Vc/AppRun.wrapped: line 6: 22887 Segmentation fault      LD_LIBRARY_PATH="$d/usr/lib":$LD_LIBRARY_PATH "$bin/hotspot" "$@"
```

**Version Info (please complete the following information):**

- Linux Kernel version:  3.10.0-1160.31.1.el7.x86_64
- perf version:3.10.0-1160.83.1.el7.x86_64.debug
- hotspot version: [most current appimage](https://github.com/KDAB/hotspot/actions/runs/7801553696/)

**Additional context**
Following the [debugging AppImage instructions](https://github.com/KDAB/hotspot/blob/master/HACKING.md#debugging-the-appimage), I see

```
(gdb) c
Continuing.
qt.xkb.compose: failed to create compose table
[New Thread 0x7f1837fff700 (LWP 12548)]
[New Thread 0x7f1834d66700 (LWP 12549)]
[New Thread 0x7f182f7fe700 (LWP 12550)]
[New Thread 0x7f184cabc700 (LWP 12553)]
[New Thread 0x7f1846569700 (LWP 12554)]
[New Thread 0x7f1845d68700 (LWP 12555)]
[New Thread 0x7f1845567700 (LWP 12556)]
[New Thread 0x7f1844d66700 (LWP 12558)]
[New Thread 0x7f18377fe700 (LWP 12562)]
[New Thread 0x7f1836ffd700 (LWP 12564)]
[New Thread 0x7f18367fc700 (LWP 12565)]
[New Thread 0x7f1835ffb700 (LWP 12566)]
[New Thread 0x7f18355da700 (LWP 12567)]
[New Thread 0x7f182ffff700 (LWP 12568)]
[New Thread 0x7f182effd700 (LWP 12569)]
[New Thread 0x7f182e7fc700 (LWP 12570)]
[Detaching after fork from child process 13110]
hotspot.disassemblyoutput: objdump binary does not support `--visualize-jumps`: "/usr/bin/objdump"
[Detaching after fork from child process 13111]
hotspot.disassemblyoutput: objdump binary does not support `--disassembler-color`: "/usr/bin/objdump"
[Detaching after fork from child process 13112]

Program received signal SIGSEGV, Segmentation fault.
0x0000000000508925 in ?? ()

(gdb) bt full
#0  0x0000000000508925 in ?? ()
No symbol table info available.
#1  0x0000000000510d7c in ?? ()
No symbol table info available.
#2  0x00000000004eec91 in ?? ()
No symbol table info available.
#3  0x00007f1861fa5f38 in QTreeView::drawRow(QPainter*, QStyleOptionViewItem const&, QModelIndex const&) const ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#4  0x00007f1861fa9df5 in QTreeView::drawTree(QPainter*, QRegion const&) const ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#5  0x00007f1861faff48 in QTreeView::paintEvent(QPaintEvent*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#6  0x00007f1861d2790e in QWidget::event(QEvent*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#7  0x00007f1861dd0c9e in QFrame::event(QEvent*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#8  0x00007f18611d2d32 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Core.so.5
No symbol table info available.
#9  0x00007f1861ce8b6e in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#10 0x00007f18611d2fba in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Core.so.5
No symbol table info available.
#11 0x00007f1861d20536 in QWidgetPrivate::sendPaintEvent(QRegion const&) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#12 0x00007f1861d20d86 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#13 0x00007f1861d2215e in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#14 0x00007f1861d21f85 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#15 0x00007f1861d21f85 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#16 0x00007f1861d20a92 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#17 0x00007f1861d2215e in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#18 0x00007f1861d21f85 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#19 0x00007f1861d20a92 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#20 0x00007f1861d2215e in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#21 0x00007f1861d21f85 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#22 0x00007f1861d20a92 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#23 0x00007f1861d2215e in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#24 0x00007f1861d20a92 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#25 0x00007f1861d2215e in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint
const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#26 0x00007f1861d20a92 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#27 0x00007f1861d2215e in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#28 0x00007f1861d20a92 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#29 0x00007f1861d2215e in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#30 0x00007f1861d21f85 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#31 0x00007f1861d20a92 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#32 0x00007f1861d2215e in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#33 0x00007f1861d20a92 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#34 0x00007f1861d2215e in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#35 0x00007f1861d21f85 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#36 0x00007f1861d21f85 in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#37 0x00007f1861d20a92 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#38 0x00007f1861d2215e in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#39 0x00007f1861d20a92 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#40 0x00007f1861d2215e in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#41 0x00007f1861d20a92 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#42 0x00007f1861d2215e in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#43 0x00007f1861d20a92 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#44 0x00007f1861d2215e in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#45 0x00007f1861d20a92 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#46 0x00007f1861d2215e in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#47 0x00007f1861d20a92 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#48 0x00007f1861d2215e in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#49 0x00007f1861d20a92 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, QFlags<QWidgetPrivate::DrawWidgetFlag>, QPainter*, QWidgetRepaintManager*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#50 0x00007f1861cf91ff in ?? () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#51 0x00007f1861d282a7 in QWidget::event(QEvent*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#52 0x00007f186302d7ac in KMainWindow::event(QEvent*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libKF5XmlGui.so.5
No symbol table info available.
#53 0x00007f18630831d8 in KXmlGuiWindow::event(QEvent*) () from /tmp/.mount_hotspou7VRGm/usr/lib/libKF5XmlGui.so.5
No symbol table info available.
#54 0x00007f1861ce8b7f in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Widgets.so.5
No symbol table info available.
#55 0x00007f18611d2fba in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Core.so.5
No symbol table info available.
#56 0x00007f18611d5d47 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Core.so.5
No symbol table info available.
#57 0x00007f1861227623 in ?? () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Core.so.5
No symbol table info available.
#58 0x00007f185b651119 in g_main_context_dispatch () from /tmp/.mount_hotspou7VRGm/usr/lib/libglib-2.0.so.0
No symbol table info available.
#59 0x00007f185b651478 in g_main_context_iterate.isra.19 () from /tmp/.mount_hotspou7VRGm/usr/lib/libglib-2.0.so.0
No symbol table info available.
#60 0x00007f185b65152c in g_main_context_iteration () from /tmp/.mount_hotspou7VRGm/usr/lib/libglib-2.0.so.0
No symbol table info available.
#61 0x00007f1861226cf4 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Core.so.5
No symbol table info available.
#62 0x00007f18611d1b3b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Core.so.5
No symbol table info available.
#63 0x00007f18611d977c in QCoreApplication::exec() () from /tmp/.mount_hotspou7VRGm/usr/lib/libQt5Core.so.5
No symbol table info available.
#64 0x0000000000442d3d in ?? ()
No symbol table info available.
#65 0x00007f1860351555 in __libc_start_main (main=0x442260, argc=2, argv=0x7ffca8d3e298, init=<optimized out>,
    fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffca8d3e288) at ../csu/libc-start.c:266
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -8842598268481307497, 4469499, 140723140944528, 0, 0, 8841012600443501719,
                8896869669805620375}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7f18642f99c3 <_dl_init+275>,
              0x7f186450d150}, data = {prev = 0x0, cleanup = 0x0, canceltype = 1680841155}}}
        not_first_call = <optimized out>
#66 0x0000000000443324 in ?? ()
No symbol table info available.

(gdb) info threads
  Id   Target Id         Frame
  35   Thread 0x7f182e7fc700 (LWP 12570) "Thread (pooled)" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  34   Thread 0x7f182effd700 (LWP 12569) "Thread (pooled)" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  33   Thread 0x7f182ffff700 (LWP 12568) "Thread (pooled)" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  32   Thread 0x7f18355da700 (LWP 12567) "Thread (pooled)" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  31   Thread 0x7f1835ffb700 (LWP 12566) "Thread (pooled)" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  30   Thread 0x7f18367fc700 (LWP 12565) "Thread (pooled)" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  29   Thread 0x7f1836ffd700 (LWP 12564) "Thread (pooled)" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  28   Thread 0x7f18377fe700 (LWP 12562) "Thread (pooled)" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  27   Thread 0x7f1844d66700 (LWP 12558) "Thread (pooled)" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  26   Thread 0x7f1845567700 (LWP 12556) "Thread (pooled)" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  25   Thread 0x7f1845d68700 (LWP 12555) "Thread (pooled)" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  24   Thread 0x7f1846569700 (LWP 12554) "Thread (pooled)" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  23   Thread 0x7f184cabc700 (LWP 12553) "Thread (pooled)" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  22   Thread 0x7f182f7fe700 (LWP 12550) "Thread (pooled)" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  21   Thread 0x7f1834d66700 (LWP 12549) "Thread (pooled)" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  20   Thread 0x7f1837fff700 (LWP 12548) "Thread (pooled)" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  19   Thread 0x7f184da7f700 (LWP 30077) "QXcbEventQueue" 0x00007f1860422ccd in poll () at ../sysdeps/unix/syscall-template.S:81
  18   Thread 0x7f182dffb700 (LWP 30409) "QDBusConnection" 0x00007f1860422ccd in poll () at ../sysdeps/unix/syscall-template.S:81
  17   Thread 0x7f182d7fa700 (LWP 30457) "GlobalQueue[01]" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  16   Thread 0x7f182cff9700 (LWP 30458) "GlobalQueue[02]" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  15   Thread 0x7f17effff700 (LWP 30459) "GlobalQueue[03]" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  14   Thread 0x7f17e7fff700 (LWP 30460) "GlobalQueue[04]" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  13   Thread 0x7f17ef7fe700 (LWP 30461) "GlobalQueue[05]" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  12   Thread 0x7f17eeffd700 (LWP 30462) "GlobalQueue[06]" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  11   Thread 0x7f17ee7fc700 (LWP 30463) "GlobalQueue[07]" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  10   Thread 0x7f17edffb700 (LWP 30464) "GlobalQueue[08]" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  9    Thread 0x7f17ed7fa700 (LWP 30466) "GlobalQueue[09]" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  8    Thread 0x7f17ecff9700 (LWP 30467) "GlobalQueue[10]" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  7    Thread 0x7f17e77fe700 (LWP 30468) "GlobalQueue[11]" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  6    Thread 0x7f17e6ffd700 (LWP 30469) "GlobalQueue[12]" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  5    Thread 0x7f17e67fc700 (LWP 30470) "GlobalQueue[13]" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  4    Thread 0x7f17e5ffb700 (LWP 30471) "GlobalQueue[14]" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  3    Thread 0x7f17e57fa700 (LWP 30472) "GlobalQueue[15]" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  2    Thread 0x7f17e4ff9700 (LWP 30473) "GlobalQueue[16]" pthread_cond_wait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
* 1    Thread 0x7f18561d1980 (LWP 30074) "hotspot" 0x0000000000508925 in ?? ()

```

If needed I could provide a coredump (hotspot.SY948.core) by mail or, preferably, inspect other threads.
In any case it seems useful to add a download with more debuginfo (for the contained libraries).

**Comment by milianw** [comment]
this crashes deep within Qt, nothing for us to fix I fear. I haven't seen this myself either. I fear I will have to close this. Reopen if you think this can be handled by us directly.

**Comment by GitMensch** [comment]
Thanks for checking.

Yes, it was the SourceCodeModel and that got fixed in the meantime.
Closed status is fine, but upstream tag is wrong.

@skrap Did you experienced something similar? If yes, please open a new bug report with your stacktrace, after checking that current continuous works fine.

**Comment by skrap** [comment]
Ah, thank you @GitMensch.  My crash was on 1.51.1 release.  I have checked with the latest "continuous" (from https://github.com/KDAB/hotspot/commit/b61451d827dd23e35c5f611e3626226a119dfa48) and the crash does not occur.  Seems that it was fixed as you say!
