### ISSUE TITLE
incompatible packages under Ubuntu 16.04.3 LTS (xenial)

### ISSUE THREAD

**Issue by DannyBoyKN** [KDAB/hotspot#96]
I had to install Qt 5.6.1 manually following this:
```
$ wget http://download.qt-project.org/official_releases/qt/5.6/5.6.1/qt-opensource-linux-x64-5.6.1.run
$ chmod +x qt-opensource-linux-x64-5.6.1.run
$ sudo ./qt-opensource-linux-x64-5.6.1.run
```
which installed it under /opt/Qt5.6.1/. To build hotspot I had to set the LD_LIBRARY_PATH=/opt/Qt5.6.1/5.6/gcc_64/lib.

'cmake ..' output is:
```
-- The CXX compiler identification is GNU 6.3.0
-- The C compiler identification is GNU 6.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found LibElf: /usr/lib/x86_64-linux-gnu/libelf.so  
-- Found ElfUtils: /usr/lib/x86_64-linux-gnu/libdw.so  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found KF5ThreadWeaver: /usr/lib/x86_64-linux-gnu/cmake/KF5ThreadWeaver/KF5ThreadWeaverConfig.cmake (found version "5.18.0") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.7") 
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Found KF5I18n: /usr/lib/x86_64-linux-gnu/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.18.0") 
-- Found KF5ConfigWidgets: /usr/lib/x86_64-linux-gnu/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake (found version "5.18.0") 
-- Found KF5CoreAddons: /usr/lib/x86_64-linux-gnu/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.18.0") 
-- Found KF5ItemViews: /usr/lib/x86_64-linux-gnu/cmake/KF5ItemViews/KF5ItemViewsConfig.cmake (found version "5.18.0") 
-- Found KF5ItemModels: /usr/lib/x86_64-linux-gnu/cmake/KF5ItemModels/KF5ItemModelsConfig.cmake (found version "5.18.0") 
-- Found KF5KIO: /usr/lib/x86_64-linux-gnu/cmake/KF5KIO/KF5KIOConfig.cmake (found version "5.18.0") 
-- Found KF5Solid: /usr/lib/x86_64-linux-gnu/cmake/KF5Solid/KF5SolidConfig.cmake (found version "5.18.0") 
-- Found KF5: success (found version "5.18.0") found components:  ThreadWeaver I18n ConfigWidgets CoreAddons ItemViews ItemModels KIO Solid 
-- 
-- The following REQUIRED packages have been found:

 * Qt5Core
 * Qt5Gui (required version >= 5.6.1)
 * Qt5Widgets
 * Qt5Network
 * Qt5Test
 * Qt5 (required version >= 5.6)
 * LibElf
 * Elfutils
 * ECM (required version >= 1.0.0)
 * Threads
 * KF5ThreadWeaver
 * Gettext
 * PythonInterp
 * KF5I18n
 * KF5ConfigWidgets
 * KF5CoreAddons
 * KF5ItemViews
 * KF5ItemModels
 * KF5KIO
 * KF5Solid
 * KF5

-- Looking for __GLIBC__
-- Looking for __GLIBC__ - found
-- Performing Test _OFFT_IS_64BIT
-- Performing Test _OFFT_IS_64BIT - Success
-- Configuring done
CMake Warning at src/CMakeLists.txt:63 (add_executable):
  Cannot generate a safe runtime search path for target hotspot because files
  in some directories may conflict with libraries in implicit directories:

    runtime library [libQt5Xml.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /opt/Qt5.6.1/5.6/gcc_64/lib
    runtime library [libQt5DBus.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /opt/Qt5.6.1/5.6/gcc_64/lib

  Some of these libraries may not be found correctly.


CMake Warning at /usr/share/ECM/modules/ECMAddTests.cmake:97 (add_executable):
  Cannot generate a safe runtime search path for target tst_timelinedelegate
  because files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libQt5Xml.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /opt/Qt5.6.1/5.6/gcc_64/lib
    runtime library [libQt5DBus.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /opt/Qt5.6.1/5.6/gcc_64/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/modeltests/CMakeLists.txt:14 (ecm_add_test)


CMake Warning at /usr/share/ECM/modules/ECMAddTests.cmake:97 (add_executable):
  Cannot generate a safe runtime search path for target tst_models because
  files in some directories may conflict with libraries in implicit
  directories:

    runtime library [libQt5Xml.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /opt/Qt5.6.1/5.6/gcc_64/lib
    runtime library [libQt5DBus.so.5] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /opt/Qt5.6.1/5.6/gcc_64/lib

  Some of these libraries may not be found correctly.
Call Stack (most recent call first):
  tests/modeltests/CMakeLists.txt:3 (ecm_add_test)


-- Generating done
-- Build files have been written to: hotspot/build-hotspot

```

I had to set some further exports for cmake:
`export Qt5_DIR=/opt/5.6/gcc_64/lib/cmake/Qt5`

Building did not output any errors nor warnings, but after executing hotspot, it crashes with a core dump (with `export QT_DEBUG_PLUGINS=1`):
```
QFactoryLoader::QFactoryLoader() checking directory path "hotspot/build-hotspot/bin/imageformats" ...
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqdds.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqgif.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqicns.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqico.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqjp2.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqjpeg.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqsvg.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqtga.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqtiff.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqwbmp.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqwebp.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/iconengines/libqsvgicon.so"
QFactoryLoader::QFactoryLoader() checking directory path "/opt/Qt5.6.1/5.6/gcc_64/plugins/accessible" ...
QFactoryLoader::QFactoryLoader() checking directory path "hotspot/build-hotspot/bin/accessible" ...
Segmentation fault (core dumped)
```
I suppose there're some library load mismatches (ref. cmake warnings). Is there a way to provide cmake with a different library path and/or get more debug outputs when starting hotspot to narrow the crash location ?

**Comment by milianw** [comment]
I think what you are doing wrong is using `LD_LIBRARY_PATH` in the first place. Unset it, and rather set `PATH` such that the 5.6.1 `qmake` is found and preferred over the outdated version. Then run `cmake` again (better start with a clean build dir).

Also not that you could skip all of this and simply use the AppImage instead.

**Comment by DannyBoyKN** [comment]
Indeed, adding `/opt/Qt5.6.1/5.6/gcc_64/bin` to PATH eliminates the warnings during `cmake .. `. Building again is also successful, however execution leads again to a core dump. I set again `export QT_DEBUG_PLUGINS=1` to see what happens:
```
...
Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/home/vitasuser/PEPS.git/tools/ExternalLibs/hotspot/build-hotspot/bin/platforms" ...
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/platforms/libqxcb.so"
QLibraryPrivate::loadPlugin failed on "/opt/Qt5.6.1/5.6/gcc_64/plugins/platforms/libqxcb.so" : "Cannot load library /opt/Qt5.6.1/5.6/gcc_64/plugins/platforms/libqxcb.so: (/usr/lib/x86_64-linux-gnu/libQt5DBus.so.5: version `Qt_5' not found (required by /opt/Qt5.6.1/5.6/gcc_64/plugins/platforms/../../lib/libQt5XcbQpa.so.5))"
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, xcb.

Reinstalling the application may fix this problem.
Aborted (core dumped)

```
The wrong plugins were loaded and I set again `export LD_LIBRARY_PATH=/opt/Qt5.6.1/5.6/gcc_64/lib`. Now there's much more going on during the startup phase (I did not copy-paste everything here):
```
$ ./bin/hotspot 
QFactoryLoader::QFactoryLoader() checking directory path "/opt/Qt5.6.1/5.6/gcc_64/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/opt/Qt5.6.1/5.6/gcc_64/plugins/platforms/libqeglfs.so"
Found metadata in lib /opt/Qt5.6.1/5.6/gcc_64/plugins/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
...
Got keys from plugin meta data ("webp")
QFactoryLoader::QFactoryLoader() checking directory path "/home/vitasuser/PEPS.git/tools/ExternalLibs/hotspot/build-hotspot/bin/imageformats" ...
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqdds.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqgif.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqicns.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqico.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqjp2.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqjpeg.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqsvg.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqtga.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqtiff.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqwbmp.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/imageformats/libqwebp.so"
loaded library "/opt/Qt5.6.1/5.6/gcc_64/plugins/iconengines/libqsvgicon.so"
QFactoryLoader::QFactoryLoader() checking directory path "/opt/Qt5.6.1/5.6/gcc_64/plugins/accessible" ...
QFactoryLoader::QFactoryLoader() checking directory path "hotspot/build-hotspot/bin/accessible" ...
Segmentation fault (core dumped)
```

> simply use the AppImage instead

What did you mean by this  ?
I would much appreciate if I could skip building everything ;-)

**Comment by DannyBoyKN** [comment]
I did re-cmake using `cmake -G "Unix Makefiles" .. -DCMAKE_BUILD_TYPE=Debug` to have the debug symbols available and rebuild hotspot again.

Now I can use '`ddd ./bin/hotspot`' to dig into the location of the crash cause. Here's the log from the debugger with the backtrace. Frame #5 points to line #62 of otspot/src/recordpage.cpp.

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./bin/hotspot'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f1dd819c428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
[Current thread is 1 (Thread 0x7f1ddbceb8c0 (LWP 20998))]
(gdb) bt
#0  0x00007f1dd819c428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
#1  0x00007f1dd819e02a in __GI_abort () at abort.c:89
#2  0x00007f1dd894b59e in QMessageLogger::fatal(char const*, ...) const () from /opt/Qt5.6.1/5.6/gcc_64/lib/libQt5Core.so.5
#3  0x00007f1dd8946df1 in qt_assert_x(char const*, char const*, char const*, int) () from /opt/Qt5.6.1/5.6/gcc_64/lib/libQt5Core.so.5
#4  0x000000000047b0c1 in QList<Solid::Device>::operator[] (this=0x7ffc5e489790, i=0) at /opt/Qt5.6.1/5.6/gcc_64/include/QtCore/qlist.h:535
#5  0x00000000004709c1 in (anonymous namespace)::isIntel () at hotspot/src/recordpage.cpp:62
#6  0x0000000000472aaa in RecordPage::RecordPage (this=0xcfd880, parent=0xdb54a0) at hotspot/src/recordpage.cpp:237
#7  0x00000000004578de in MainWindow::MainWindow (this=0xdb54a0, parent=0x0) at hotspot/src/mainwindow.cpp:91
#8  0x00000000004260ab in main (argc=1, argv=0x7ffc5e489e28) at hotspot/src/main.cpp:132
(gdb) fr 5
#5  0x00000000004709c1 in (anonymous namespace)::isIntel () at hotspot/src/recordpage.cpp:62
```

hotspot/src/recordpage.cpp:62
```
      58 namespace {
      59 bool isIntel()
      60 {
      61     const auto list = Solid::Device::listFromType(Solid::DeviceInterface::Processor, QString());
      62     Solid::Device device = list[0];
```
Does this help to identify the cause ?

**Comment by milianw** [comment]
To download the AppImage, see the link on this page: https://github.com/KDAB/hotspot/releases/tag/v1.1.0 If you don't know what an AppImage is, see https://appimage.org/

And yes, thanks for the debugging effort - I will fix this issue now!
